; ─── APP ────────────────────────────────────────────────────────────────────
date.timezone = Europe/Warsaw
memory_limit = 256M
upload_max_filesize = 64M
post_max_size = 64M
max_execution_time = 60

; ─── OPCACHE (dev — wyłączone dla wygody reloadów) ───────────────────────────
opcache.enable = 0
opcache.enable_cli = 0
